### ISSUE TITLE
Add support for cyrillic folders

### ISSUE THREAD

**Issue by asm0dey** [rpuntaie/mutt-wizard#7]
When syncing mail with Gmail if I have folder with name like `Рассылки` it has some weird name in mutt, starting with umpersand. 

Is it possible to fix it?

**Comment by rpuntaie** [comment]
The reason, I think, was that I didn't rely on mbsync to retrieve the mailbox list, but on a python script. It turns out that imap uses a special encoding that python does not consider yet.

The solution: 
I've changed the python code to decode using imap4-utf-7.

I can't test this, because I have no mail account with non-latin alphabet.
It still works for latin alphabet.
Could you test with the current github version and report here?
If it work, I will make a new release.

**Comment by asm0dey** [comment]
Yep it works, thank you!

**Comment by rpuntaie** [comment]
Thanks for testing.
I made a new release v2.0.3.

**Comment by asm0dey** [comment]
Hah, I can see cyryllic-named folders, but they're empty and everything is still being synced to strange-named ones :(

**Comment by rpuntaie** [comment]
`mw` only fetches the mailbox names for IMAP. That was corrected.

Other than that the dependencies are used.

If you chose "online" for the account, then mutt does the synchronization.
Then maybe this is still a problem:
https://unix.stackexchange.com/questions/140372/greek-characters-in-mutts-sidebar-mailboxes-names-sourced-via-offlineimap

For "offline", `mbsync` gets the mails for IMAP, and `getmail` for POP3.

I know that `getmail` does imap-utf-7 decoding, because I just ported it to Python 3.
`getmail` is used for IMAP, too, if the `$XDG_CONFIG_HOME/getmail` has the according account config file. In the v2.0.3, if no mbsync is available, a `getmail` config is created also for IMAP.

In your case you most likely use `mbsync`.
Regarding `mbsync` I found 

- https://github.com/LukeSmithxyz/mutt-wizard/issues/149#issuecomment-488390918

You can try that archlinux patched version.

For reference:
https://sourceforge.net/p/isync/bugs/47/

**Comment by asm0dey** [comment]
Wow, thank yu for research!

I'll try those patched version and will give you know!

On 20/05/12 02:48AM, Roland Puntaier wrote:
> `mw` only fetches the mailbox names for IMAP. That was corrected.
> 
> Other than that the dependencies are used.
> 
> If you chose "online" for the account, then mutt does the synchronization.
> Then maybe this is still a problem:
> https://unix.stackexchange.com/questions/140372/greek-characters-in-mutts-sidebar-mailboxes-names-sourced-via-offlineimap
> 
> For "offline", `mbsync` gets the mails for IMAP, and `getmail` for POP3.
> 
> I know that `getmail` does imap-utf-7 decoding, because I just ported it to Python 3.
> `getmail` is used for IMAP, too, if the `$XDG_CONFIG_HOME/getmail` has the according account config file. In the v2.0.3, if no mbsync is available, a `getmail` config is created also for IMAP.
> 
> In your case you most likely use `mbsync`.
> Regarding `mbsync` I found 
> 
> - https://github.com/LukeSmithxyz/mutt-wizard/issues/149#issuecomment-488390918
> 
> If you use that archlinux patched version, it should work.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/rpuntaie/mailwizard/issues/7#issuecomment-627235004

-- 
Regards,
Pasha

Big Data Tools @ JetBrains

**Comment by asm0dey** [comment]
Oops, I can't try it because mailwizard-git requires isync :(
On 20/05/12 02:48AM, Roland Puntaier wrote:
> `mw` only fetches the mailbox names for IMAP. That was corrected.
> 
> Other than that the dependencies are used.
> 
> If you chose "online" for the account, then mutt does the synchronization.
> Then maybe this is still a problem:
> https://unix.stackexchange.com/questions/140372/greek-characters-in-mutts-sidebar-mailboxes-names-sourced-via-offlineimap
> 
> For "offline", `mbsync` gets the mails for IMAP, and `getmail` for POP3.
> 
> I know that `getmail` does imap-utf-7 decoding, because I just ported it to Python 3.
> `getmail` is used for IMAP, too, if the `$XDG_CONFIG_HOME/getmail` has the according account config file. In the v2.0.3, if no mbsync is available, a `getmail` config is created also for IMAP.
> 
> In your case you most likely use `mbsync`.
> Regarding `mbsync` I found 
> 
> - https://github.com/LukeSmithxyz/mutt-wizard/issues/149#issuecomment-488390918
> 
> If you use that archlinux patched version, it should work.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/rpuntaie/mailwizard/issues/7#issuecomment-627235004

-- 
Regards,
Pasha

Big Data Tools @ JetBrains

**Comment by rpuntaie** [comment]
You can try by directly using the github version. First remove `mailwizard-git` and `isync` from your system. Then

```
git clone https://github.com/rpuntaie/mailwizard
cd mailwizard
sudo make install
```
